gralloc3: Remove unused -ldl cflag
Fixes the following compilation error:
clang++: error: -ldl: 'linker' input unused [-Werror,-Wunused-command-line-argument]